### ISSUE TITLE
Implement `git gud show-tree` to display tree in `.spec` format

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#11]
It would be great for the user to have a simple way to display the current tree. Simply display the current tree in the spec format this project uses when specifying levels.

The spec format can be seen in the level directories ie 'levels/merging/_octopus/test.spec'

To do this, you may also want to implement `operations.get_topology()`, which may be used for other functions, but this is not necessary.

**Comment by bthayer2365** [comment]
@parkmichael777 Can you work on this with the command alias you showed me from before that showed the git tree? You'll need to make use of GitPython, but essentially you're just running the same command that you showed me. We don't need to do it in the `.spec` format.

**Comment by parkmichael777** [comment]
Sure, I can take a look at it!
