### ISSUE TITLE
KeyError when using `git gud load`

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#18]
I'd like to have this fail gracefully instead of just showing the stack trace for the KeyError.

The KeyErrors happen when providing a level name or a challenge name that doesn't exist.

Instead of showing the KeyError, we should provide a message that says "Level X doesn't exist" or "Challenge Y doesn't exist" and something like "To view challenges/levels, use `git gud challenges` or `git gud levels`"

**Comment by rblcoder** [comment]
Hi @bthayer2365 , does this mean we need to modify get_challenge in the class Operator in operations.py, put a try except around all_levels[level_name].challenges[challenge_name] and raise an exception with the message "To view challenges/levels, use git gud challenges or git gud levels"

**Comment by bthayer2365** [comment]
Hi @rblcoder ,

You're right. We do need to modify get_challenge. I was thinking that instead of raising an exception, we can just print what happened directly to the terminal to make it look prettier. 

I was also thinking about separating that line into two statements, one getting the level, one getting the challenge. Before running each step, we can actually check to see if the KeyError is going to occur by using if statements. If you want, you can use `if level_name in all_levels:` since that KeyError only occurs when level_name is not in all_levels. You can do something similar to check if the same thing happens for the challenges. The message depends on which part fails. For example, if you misspell intro and instead write "git gud load iintro merging", when it looks for the level "iintro", it won't be in all_levels, and you can output "Level "intro" does not exist" and then do something similar for the challenges.
