### ISSUE TITLE
Change the data structure for all_levels and all_challenges to allow indexing

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#23]
all_levels is defined in levels/\_\_init\_\_.py
all_challenges is defined in levels/intro/\_\_init\_\_.py and in levels/merging/\_\_init\_\_.py

Currently, they're both implemented using `OrderedDict`, but that's not as useful as it could be. Dicts allow us to access levels/challenges by name and preserving the order allows us to know which one comes after the next (duh).

Currently, we run into situations, where we need to run
```
level1 = next(iter(all_levels))
challenge1 = next(iter(level1.challenges))
```

but this is hard to read, so I would like that same code to look like
```
level1 = all_levels[0]
challenges = level1.challenges[0]
```

OrderedDict doesn't let us do that because it uses a linked list internally, which allows for fast insertion, deletion and iteration, but makes accessing elements by index very challenging. I'd like to use a different data structure that allows for both indexing like a list and key/value lookups like a dictionary. 

There should be something in Python's standard library that we can use, so we should not have to implement our own. If for some reason there isn't anything in the standard library, you can comment here and we can figure something else out.

After changing the data structure, we should go and change all the code that uses `next(iter(...))`

**Comment by Ishan1742** [comment]
I am not sure if there is a data structure in the standard library but we might be able to do it using hashing. We hash the level string to a index and at that index we store the values for challenges. 

When we have a level_name we can compute it's hash and look it up at that index.
Or we could just iterate through all the indexes when we need to.

The issue here is that a string can be hashed to the same index but since we are the only ones creating the levels we can set the hash values ourselves instead of an algorithm. 

dictionary for levels
\-
| "intro" : 0
| "merging" : 1
\-

list of list for challenges

\-
| 0 -> [challenge_1, challenge_2, challenge_3]
| 1 -> [challenge_1, challenge_2]
\-

**Comment by bthayer2365** [comment]
Hey @Ishan1742 , thanks for the suggestion. If we're going to do that, I think it would be best to wrap that in our own data structure, so the underlying mechanism would be your idea, and then we add the `__getitem__` method to the `Level` class so we don't have to worry about accessing the data structures ourselves.

For example, we should be able to do `intro['committing']` and `intro[0]`, and they would return the same challenge. `type(intro)` would also be equal to `Level`.

In order to do the same thing to get access to each levels, we might have an `AllLevels` object that we can define in `gitgud/levels/util.py` and use in a similar fashion.

Together, we might have:
#### `gitgud/levels/intro/__init__.py`
```
level = Level('intro', [
    BasicChallenge('committing'...),
    BasicChallenge('branching'...)
]
```

#### `gitgud/levels/__init__.py`
```
from gitgud.levels.intro import level as intro_level
from gitgud.levels.intro import level as merging_level
all_levels = AllLevels([
    intro_level,
    merging_level
])
```

`Level` and `AllLevels` would act in a similar way and now, because we're setting things using our own method, internally we can run commands like `challenge.name` to set the values of the data structures you proposed. Similarly, we can now move the `_add_next_challenges()` code into `AllLevels.__init__`

This might be a helpful resource: [https://docs.python.org/3/reference/datamodel.html#object.\_\_getitem\_\_](https://docs.python.org/3/reference/datamodel.html#object.__getitem__)


This might take a bit of work, but it'll be hugely helpful, and hopefully great experience for you too! If you think you're up for it, go for it and feel free to ask me questions. I'll be here!

**Comment by Ishan1742** [comment]
I can work on it. I might take some time. 
If anyone has a better idea of implementing it feel free to take up this issue.

**Comment by sahansk2** [comment]
I can start trying to work on this.

**Comment by bthayer2365** [comment]
Thanks @sahansk2 let me know if you need any help. @Ishan1742 I will be posting more issues by Saturday and can tag you once they're up if you're still interested

**Comment by Ishan1742** [comment]
I'd love to contribute but I have exams coming up next week so it'll be a week after that when I'd be able to work on those issues.

**Comment by bthayer2365** [comment]
No problem, good luck on exams!

**Comment by sahansk2** [comment]
With #26 in mind, do we no longer want to access the levels by name? Or do you want to add loading by level/challenge index as an extra functionality?

**Comment by bthayer2365** [comment]
I would like to have both functionality. I'm assuming some people will still want to access by name. I'll clarify #26
