### ISSUE TITLE
When setting up level, order commits using timestamps

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#25]
When we create the commits during the level setup process right now, they're all made at the same time and some of them end up with the same timestamp.  If we run git log, then commits show up out of order.

To fix, we can just set the time. When looking at the spec file, that should be the order of the timestamps and all timestamps should come before the time at which `create_tree` is called so that any commits created later on by the user don't end up with a timestamp before the commits Git Gud created

Relevant method is `create_tree` in gitgud/operations.py

**Comment by bthayer2365** [comment]
@sahansk2 Do you think you can take this?

**Comment by sahansk2** [comment]
I think so -- it might take a bit to figure out gitpython, but I'll have a go!
