### ISSUE TITLE
Change the contributing file so that every sentence is on its own line

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#35]
Markdown allows you to write a paragraph with using mutliple lines. It'll automatically put text that are on new lines right after one another. View the raw text in [CONTRIBUTING.md](https://github.com/bthayer2365/git-gud/edit/master/CONTRIBUTING.md) to see how I've gotten started.

You should be able to do the pull request directly on github.

This is useful because git shows that a line is changed, and if a line is an entire paragraph, then it might not be clear what the exact change is.

**Comment by clussell** [comment]
Can I take this?

**Comment by bthayer2365** [comment]
Closed by #37
