### ISSUE TITLE
Git.AutoInterrupt.__del__() OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#44]
Unfortunately on Windows, we're getting this beastly error, which is caused by GitPython, not by Git Gud. If someone wants to go there and fix the issue, that would be terrific, but it seems like a tough issue. I may take it on myself at some point.

If someone would like to find a workaround for us specifically, that would also be helpful.

Here's the link to the issue on the GitPython repo: https://github.com/gitpython-developers/GitPython/issues/935

**Comment by thecnoNSMB** [comment]
Has this regressed? I'm experiencing the same issue.

**Comment by benthayer** [comment]
This issue has happened previously in multiple situations. Some have been fixed but it's possible there is another error. Can you post a new issue with steps to reproduce?

**Comment by thecnoNSMB** [comment]
> This issue has happened previously in multiple situations. Some have been fixed but it's possible there is another error. Can you post a new issue with steps to reproduce?

Done: #348
