### ISSUE TITLE
Rename the `merging` level to `extras`

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#46]
We're going to add the ability to run `git gud load <challenge>`, but in order for that to work, we need to first make sure there are no naming collisions between levels and challenges, so for the meantime, I think it makes sense to put the octopus merging challenge in the `extras` level until we have more levels that it might make sense to group it with.

We should also update `CONTRIBUTING.md`, which has a reference to that level with the new path.

The level is located under `gitgud/levels/merging/`

**Comment by TSSlade** [comment]
Have made some changes to address this issue. Keep getting
`error: failed to push some refs to 'git@github.com:bthayer2365/git-gud.git'`.

I think I may need to be given access rights? If so, please provide!
