### ISSUE TITLE
Log commit hashes when creating commits

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#62]
This is applicable to `git gud commit` and calls to `create_tree()`. This should be done inside the  `create_tree` and inside the `handle_commit` method.

This is useful because it gives the user information about the events that are happening to create the current tree.

Edit: logging for `git gud commit` is complete due to #71. We still need to do this for `create_tree()`

**Comment by cheedep** [comment]
@bthayer2365 how should the messages look like. Is it possible to get an example for each of `git gud commit` and `create_tree()`

For example this is what I have for `git gud commit`
![image](https://user-images.githubusercontent.com/526575/67453858-ee3b8880-f5dc-11e9-861c-cacdcab11da5.png)

I am yet to figure out the create_tree()

**Comment by bthayer2365** [comment]
What you have there is good, thanks for working on this.

I pasted below what it normally looks like when committing. 
```
[master f7778e8] Added 3
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 3
```

I think we can cut down the hash to 8 characters like git does normally and maybe change the message you have to be prettier.

So, something like 
```
...
Simulating: git commit -m "3"
New Commit: d77413e8
```

Also, I took a look at your code, and unfortunately, for comparability reasons, we can't use f-strings 😢 but oh I do love them so much! f-strings were introduced in python 3.6, and some people only have 3.5 or lower, so to make it easier for everyone to install, we need to avoid using f-strings in favor of `'string'.format()`
