### ISSUE TITLE
Add reverting notation to spec files

### ISSUE THREAD

**Issue by bthayer2365** [bthayer2365/git-gud#91]
The conversation has been taking place as part of #66, which is adding a level that shows the user how to revert. The idea is to list ~~`-1`~~ `1-` in the spec file if that commit reverts commit 1.

**Comment by bthayer2365** [comment]
@parkmichael777 Instead of using `-1`, let's use `1-`. I think `-1` makes more sense, but it's not a valid tag. `1-` is a valid tag, so we'll be able to tag the commit with the same thing we specify in the spec file and make it easier to access.

**Comment by parkmichael777** [comment]
Okay this is finished. I wrote a static helper function that is called three times, once for the branches, once for the commits themselves, and once for the parents. The code detects "Revert" (case sensitive and without quotes) and then replaces looks for a string "#" (with quotes and only single digits). Then it matches the string to a dictionary and replaces the name of the commit. Right now it can only detect single digits; however, this is scalable (just add entries to the dictionary)—obviously, it would be tedious to add a bunch of numbers, but I don't think we'll need to for our tests... Also, as you requested, the code replaces "Revert #" with "#-"; however, if the user modifies the default commit message, say "Revert #:wq", it will not work. This ultimately goes back to us not being able to control the message. Besides those two things, the code works as intended—I will push it via the reverting branch.
